### ISSUE TITLE
demo url please

### ISSUE THREAD

**Issue by johnfelipe** [parliamentwatch/parliamentwatch#1]
Real demo url please

**Comment by hekele** [comment]
Here you go: 
- Blog: https://www.abgeordnetenwatch.de/blog
- Parliament Landingpage: https://www.abgeordnetenwatch.de/eu
- Profiles Overview: https://www.abgeordnetenwatch.de/hamburg/profile
- Profile: https://www.abgeordnetenwatch.de/profile/dennis-gladiator/archive/71233
- Petitions: https://www.abgeordnetenwatch.de/petitionen
