### ISSUE TITLE
Could not get backup from backups.parliamentwatch.org

### ISSUE THREAD

**Issue by Majid110** [parliamentwatch/parliamentwatch#411]
Hi, 
Step 4 of installation needs root password for downloading backup file:

> $ curl -f -u root https://backups.parliamentwatch.org/abgeordnetenwatch.de/abgeordnetenwatch.de_latest.sql.gz > provisioning/var/backup/mysql/abgeordnetenwatch.de_latest.sql.gz

how can download it?

**Comment by tobiberlin** [comment]
Unfortunately it is not possible to download the backup. We are currently in the process of re-building our project on Drupal 8 and during this work we will work on a proper open source code - at the moment we are not able to offer you access to the database backups due to data protection reasons.
