### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by derhuerst** [parliamentwatch/parliamentwatch#7]
`https://www.abgeordnetenwatch.de/` permanently redirects to `http://www.abgeordnetenwatch.de/` (which is unencrypted). For websites in general, especially for censorship-sensitive data like political opinions.

Now that SSL certificates are free and widely available, there's basically no reason not to enforce HTTPS. See [an intro to HTTPS](https://https.cio.gov/faq/) as well as [Let's Encrypt](https://letsencrypt.org/getting-started/) for further advice.

**Comment by sruh** [comment]
Thank you, this will be fixed soon when the http-only-part is discontinued. A large part of the site (blog, petitions, current parliaments) is already available via https. Eventually, the site should be https-only.

**Comment by sruh** [comment]
Entire site has been moved to https.

**Comment by 5chdn** [comment]
@derhuerst :-)

@sruh :-)
